wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1646977721
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 17
      4: 3.9.0
      5: 0.12.11
      8:
      - 5
      10:
      - 3
