wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1650262601
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 17
      4: 3.8.10
      5: 0.12.10
      8:
      - 5
      10:
      - 3
